### ISSUE TITLE
Invalid Signature

### ISSUE THREAD

**Issue by dl748** [department-stockholm/aws-signature-v4#10]
For the new Websocket API calls, this function generates an invalid signature due to it not processing url paths correctly

**Comment by slaskis** [comment]
Could you provide an example?

**Comment by dl748** [comment]
example url  GET https://xxxxxxxxxx.execute-api.us-east-1.amazonaws.com/myStage/@connections

canonicalRequest is created with

`GET
/myStage/@connections


<hexpayloadhash>`

should be

`GET
/myStage/%40connections


<hexpayloadhash>`

i made a patch to fix my code as follows

`  var canonicalRequest = exports.createCanonicalRequest(
    method,
    path.split(/\//g).map((v) => encodeURIComponent(v)).join('/'),
    query,
    options.headers,
    payload
  );`

**Comment by slaskis** [comment]
Great example, thanks! I'm surprised this is not caught by their own official test suite.

I'm currently quite busy so this might have to be a weekend project but I'd happily accept a PR if you would provide one with test that shows how this failed and is then fixed.

**Comment by awilson28** [comment]
@dl748 Mind providing the code you used to sign your connections url (ex: https://xxxxxxxxxx.execute-api.us-east-1.amazonaws.com/myStage/@connections)? I'm trying to do this as well. A full example would be greatly appreciated.

**Comment by dl748** [comment]
@awilson28 I already did, see above.

**Comment by dl748** [comment]
Created a pull request for this issue
