### ISSUE TITLE
Expires doesn't work properly on IoT mqtt over wss and v4

### ISSUE THREAD

**Issue by fyn-dev** [department-stockholm/aws-signature-v4#6]
Not sure if it issue of AWS or issue with your library that doesn't proper sign expires. 

Here is my code:

```
const v4 = require('aws-signature-v4');
const crypto = require('crypto');
const mqtt = require('mqtt');

const url = v4.createPresignedURL(
        'GET',
        'XXXXXXXXXXXXXXXXXX', // Your IoT end point here
        '/mqtt',
        'iotdevicegateway',
        crypto.createHash('sha256').update('', 'utf8').digest('hex'),
        {
            'key': 'XXXXXXXXXXXXXXXXXXXX', // your AWS access key
            'secret': 'XXXXXXXXXXXXXXXXXXX', //your AWS access secret
            'protocol': 'wss',
            'region': 'ap-southeast-1',
            'expires': 172800
        }
      );

setTimeout(() => {
   const client = mqtt.connect(url);

   client.on('connect', () => {
        console.info("CONNECTED!");
      });

   client.on('close', () => {
          console.warn("CLIENT CLOSED!!");
            client.end();
      });
}, 600000);
```
It works fine if u connecting using this signed url instantly or in a couple of minutes, but if you try to connect in 10 or more minutes then you facing issue, url become expired. Why? It signed for at least 48 hours. 
I'm using latest 1.2.1 version

**Comment by slaskis** [comment]
Do the `X-Amz-Expires` and `X-Amz-Date` headers look correct?

**Comment by slaskis** [comment]
I've tried this out myself now with the example you provided and ran it a few times on master and was unable to get it to expire, it connected nicely. 

Not sure what was your issue though.

Feel free to open again if you still have issues though!
